# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\MODULE 8\Ex127\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LÊ HOÀI THÀNH DANH")
        MainWindow.resize(507, 405)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelF = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelF.setGeometry(QtCore.QRect(70, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelF.setFont(font)
        self.labelF.setObjectName("labelF")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.labelC = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelC.setGeometry(QtCore.QRect(80, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelC.setFont(font)
        self.labelC.setObjectName("labelC")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 130, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.labelC_kq = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelC_kq.setGeometry(QtCore.QRect(270, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelC_kq.setFont(font)
        self.labelC_kq.setObjectName("labelC_kq")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LÊ HOÀI THÀNH DANH"))
        self.labelF.setText(_translate("MainWindow", "Fahrenheit (F):"))
        self.labelC.setText(_translate("MainWindow", "Celsius (C):"))
        self.pushButton.setText(_translate("MainWindow", "CONVERT"))
        self.labelC_kq.setText(_translate("MainWindow", " "))
