# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\MODULE 8\Ex124\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titlelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Titlelabel.setGeometry(QtCore.QRect(20, 0, 771, 61))
        self.Titlelabel.setObjectName("Titlelabel")
        self.pushButton_png = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_png.setGeometry(QtCore.QRect(192, 120, 121, 28))
        self.pushButton_png.setObjectName("pushButton_png")
        self.pushButton_if = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_if.setGeometry(QtCore.QRect(390, 120, 121, 28))
        self.pushButton_if.setObjectName("pushButton_if")
        self.pushButton_center = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_center.setGeometry(QtCore.QRect(540, 70, 93, 28))
        self.pushButton_center.setObjectName("pushButton_center")
        self.pushButton_change = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_change.setGeometry(QtCore.QRect(60, 70, 93, 28))
        self.pushButton_change.setObjectName("pushButton_change")
        self.pushButton_font = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_font.setGeometry(QtCore.QRect(170, 70, 93, 28))
        self.pushButton_font.setObjectName("pushButton_font")
        self.pushButton_right = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_right.setGeometry(QtCore.QRect(650, 70, 93, 28))
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_left = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_left.setGeometry(QtCore.QRect(430, 70, 93, 28))
        self.pushButton_left.setObjectName("pushButton_left")
        self.label_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(190, 150, 391, 401))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("C:\\Users\\ACER\\PycharmProjects\\MODULE 8\\Ex124\\images/image1.jpg"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titlelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Thành Danh</span><span style=\" font-weight:600;\"/></p></body></html>"))
        self.pushButton_png.setText(_translate("MainWindow", "Show .PNG Format "))
        self.pushButton_if.setText(_translate("MainWindow", "Show.GIF Format "))
        self.pushButton_center.setText(_translate("MainWindow", "Align Center"))
        self.pushButton_change.setText(_translate("MainWindow", "Change Text"))
        self.pushButton_font.setText(_translate("MainWindow", "Font Size ++"))
        self.pushButton_right.setText(_translate("MainWindow", "Align Right"))
        self.pushButton_left.setText(_translate("MainWindow", "Align Left"))
