# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\MODULE 8\Ex128\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 405)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Calendar = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Calendar.setGeometry(QtCore.QRect(70, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Calendar.setFont(font)
        self.label_Calendar.setObjectName("label_Calendar")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_Lunar = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Lunar.setGeometry(QtCore.QRect(80, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Lunar.setFont(font)
        self.label_Lunar.setObjectName("label_Lunar")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 130, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_Lunar_tranfer = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Lunar_tranfer.setGeometry(QtCore.QRect(270, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Lunar_tranfer.setFont(font)
        self.label_Lunar_tranfer.setText("")
        self.label_Lunar_tranfer.setObjectName("label_Lunar_tranfer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Calendar.setText(_translate("MainWindow", "Calendar Year:"))
        self.label_Lunar.setText(_translate("MainWindow", "Lunar Year:"))
        self.pushButton.setText(_translate("MainWindow", "TRANFER"))
